spring:
  application:
    name: service-gateway

    
  ##Gatewat configuration : 

  cloud:
    gateway:
      routes:
          
          #service des professeurs : 
        - id: service-professeurs
          uri: lb://service-professeurs
          predicates:
          - Path=/service-professeurs/**
          filters:
          - StripPrefix=1
          
            #service des login : 
        - id: service-login
          uri: lb://service-login
          predicates:
          - Path=/service-login/**
          filters:
          - StripPrefix=1
          
           #service des cours : 
        - id: service-cours
          uri: lb://service-cours
          predicates:
          - Path=/service-cours/**
          filters:
          - StripPrefix=1
          
           #service des etudiants : 
        - id: service-etudiants
          uri: lb://service-etudiants
          predicates:
          - Path=/service-etudiants/**
          filters:
          - StripPrefix=1
          
           #service des notes : 
        - id: service-notes
          uri: lb://service-notes
          predicates:
          - Path=/service-notes/**
          filters:
          - StripPrefix=1
          
        
        
server:
  port: 8080
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/     
      
      
 
