spring:
  application:
    name: service-gateway

    
  ##Gateway configuration : 

  cloud:
    gateway:
      routes:

          #service des professeurs : 
        - id: service-professeurs
          uri: lb://service-professeurs
          predicates:
          - Path=/service-professeurs/**
          filters:
          - StripPrefix=1
          
            #service de login : 
        - id: service-login
          uri: lb://service-login
          predicates:
          - Path=/service-login/**
          filters:
          - StripPrefix=1
          
        
        
server:
  port: 8080
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/     
      
      
 
