spring:
  application:
    name: service-gateway

    
  ##Gatewat configuration : 

  cloud:
    gateway:
      routes:
        #service 1 : 
        - id: service1
          uri: lb://service1
          predicates:
            - Path=/service1/**
          filters:
          - StripPrefix=1
        
        #service 2 : 
        - id: service2
          uri: lb://service2
          predicates:
          - Path=/service2/**
          filters:
          - StripPrefix=1
          
          #service des professeurs : 
        - id: service-professeurs
          uri: lb://service-professeurs
          predicates:
          - Path=/service-professeurs/**
          filters:
          - StripPrefix=1
          
            #service des login : 
        - id: service-login
          uri: lb://service-login
          predicates:
          - Path=/service-login/**
          filters:
          - StripPrefix=1
          
        
        
server:
  port: 8080
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/     
      
      
 
